#!/bin/sh

# Instatiate instance called california
gcloud beta compute instances create california --project=proud-voice-354916 --zone=us-west4-b --machine-type=e2-medium --network-interface=network-tier=PREMIUM,subnet=default --metadata=^,@^ssh-keys=cadumas01:ecdsa-sha2-nistp256\ AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHPWQFruKlV4cFTycuTafIE2vyXhgBCCFkiLK\+rsxRndd3g3MJ\+vD2B2C2GimyAAm2CNFWtnLPIz5TwbAeUGlY8=\ google-ssh\ \{\"userName\":\"cadumas01@gmail.com\",\"expireOn\":\"2022-06-30T19:19:10\+0000\"\}$'\n'cadumas01:ssh-rsa\ AAAAB3NzaC1yc2EAAAADAQABAAABAHAjI93u32V4v5QxCerS/zVx3rvhkJhEHITZ5376F1DfFeYqaLc3VblT86F7IgxXtWextsz\+AFXI58ZG2Bz\+kbujUlqYEGrHzZ3DzS1msJWwULsunvn8xkSMAEkFeaWp33MrIF3t7wEei0cpiv99L3p0vr5/EFZ/dN4lb16\+LLt1bZ/zKE2N\+a47i3x3fUOqmnhG1rTA5XxENHbGdF5\+rYSbHpJGzTFSgSLBoqxU9MGPRRhTZVRerOd2oKkEJjisD9r3qyUJcNpHr6VlvQ9HdAPtm4pqUAJQ0\+V8\+6yKwDXX6apvfZZH2QYEhmnaupebW08O/mSVUqDz10ulfKfsNEc=\ google-ssh\ \{\"userName\":\"cadumas01@gmail.com\",\"expireOn\":\"2022-06-30T19:19:24\+0000\"\} --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=150111394255-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --min-cpu-platform=Automatic --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any --source-machine-image=gus-demo-v1

# Instatiate instance called virginia
gcloud beta compute instances create virginia --project=proud-voice-354916 --zone=us-west4-b --machine-type=e2-medium --network-interface=network-tier=PREMIUM,subnet=default --metadata=^,@^ssh-keys=cadumas01:ecdsa-sha2-nistp256\ AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHPWQFruKlV4cFTycuTafIE2vyXhgBCCFkiLK\+rsxRndd3g3MJ\+vD2B2C2GimyAAm2CNFWtnLPIz5TwbAeUGlY8=\ google-ssh\ \{\"userName\":\"cadumas01@gmail.com\",\"expireOn\":\"2022-06-30T19:19:10\+0000\"\}$'\n'cadumas01:ssh-rsa\ AAAAB3NzaC1yc2EAAAADAQABAAABAHAjI93u32V4v5QxCerS/zVx3rvhkJhEHITZ5376F1DfFeYqaLc3VblT86F7IgxXtWextsz\+AFXI58ZG2Bz\+kbujUlqYEGrHzZ3DzS1msJWwULsunvn8xkSMAEkFeaWp33MrIF3t7wEei0cpiv99L3p0vr5/EFZ/dN4lb16\+LLt1bZ/zKE2N\+a47i3x3fUOqmnhG1rTA5XxENHbGdF5\+rYSbHpJGzTFSgSLBoqxU9MGPRRhTZVRerOd2oKkEJjisD9r3qyUJcNpHr6VlvQ9HdAPtm4pqUAJQ0\+V8\+6yKwDXX6apvfZZH2QYEhmnaupebW08O/mSVUqDz10ulfKfsNEc=\ google-ssh\ \{\"userName\":\"cadumas01@gmail.com\",\"expireOn\":\"2022-06-30T19:19:24\+0000\"\} --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=150111394255-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --min-cpu-platform=Automatic --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any --source-machine-image=gus-demo-v1

# Instatiate instance called ireland
gcloud beta compute instances create ireland --project=proud-voice-354916 --zone=us-west4-b --machine-type=e2-medium --network-interface=network-tier=PREMIUM,subnet=default --metadata=^,@^ssh-keys=cadumas01:ecdsa-sha2-nistp256\ AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHPWQFruKlV4cFTycuTafIE2vyXhgBCCFkiLK\+rsxRndd3g3MJ\+vD2B2C2GimyAAm2CNFWtnLPIz5TwbAeUGlY8=\ google-ssh\ \{\"userName\":\"cadumas01@gmail.com\",\"expireOn\":\"2022-06-30T19:19:10\+0000\"\}$'\n'cadumas01:ssh-rsa\ AAAAB3NzaC1yc2EAAAADAQABAAABAHAjI93u32V4v5QxCerS/zVx3rvhkJhEHITZ5376F1DfFeYqaLc3VblT86F7IgxXtWextsz\+AFXI58ZG2Bz\+kbujUlqYEGrHzZ3DzS1msJWwULsunvn8xkSMAEkFeaWp33MrIF3t7wEei0cpiv99L3p0vr5/EFZ/dN4lb16\+LLt1bZ/zKE2N\+a47i3x3fUOqmnhG1rTA5XxENHbGdF5\+rYSbHpJGzTFSgSLBoqxU9MGPRRhTZVRerOd2oKkEJjisD9r3qyUJcNpHr6VlvQ9HdAPtm4pqUAJQ0\+V8\+6yKwDXX6apvfZZH2QYEhmnaupebW08O/mSVUqDz10ulfKfsNEc=\ google-ssh\ \{\"userName\":\"cadumas01@gmail.com\",\"expireOn\":\"2022-06-30T19:19:24\+0000\"\} --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=150111394255-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --min-cpu-platform=Automatic --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any --source-machine-image=gus-demo-v1

# Instatiate instance called control
gcloud beta compute instances create control --project=proud-voice-354916 --zone=us-west4-b --machine-type=e2-medium --network-interface=network-tier=PREMIUM,subnet=default --metadata=^,@^ssh-keys=cadumas01:ecdsa-sha2-nistp256\ AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHPWQFruKlV4cFTycuTafIE2vyXhgBCCFkiLK\+rsxRndd3g3MJ\+vD2B2C2GimyAAm2CNFWtnLPIz5TwbAeUGlY8=\ google-ssh\ \{\"userName\":\"cadumas01@gmail.com\",\"expireOn\":\"2022-06-30T19:19:10\+0000\"\}$'\n'cadumas01:ssh-rsa\ AAAAB3NzaC1yc2EAAAADAQABAAABAHAjI93u32V4v5QxCerS/zVx3rvhkJhEHITZ5376F1DfFeYqaLc3VblT86F7IgxXtWextsz\+AFXI58ZG2Bz\+kbujUlqYEGrHzZ3DzS1msJWwULsunvn8xkSMAEkFeaWp33MrIF3t7wEei0cpiv99L3p0vr5/EFZ/dN4lb16\+LLt1bZ/zKE2N\+a47i3x3fUOqmnhG1rTA5XxENHbGdF5\+rYSbHpJGzTFSgSLBoqxU9MGPRRhTZVRerOd2oKkEJjisD9r3qyUJcNpHr6VlvQ9HdAPtm4pqUAJQ0\+V8\+6yKwDXX6apvfZZH2QYEhmnaupebW08O/mSVUqDz10ulfKfsNEc=\ google-ssh\ \{\"userName\":\"cadumas01@gmail.com\",\"expireOn\":\"2022-06-30T19:19:24\+0000\"\} --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=150111394255-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --min-cpu-platform=Automatic --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any --source-machine-image=gus-demo-v1

